name: OSV-Scanner
on:
  pull_request:
  merge_group:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  scan-pr:
    permissions:
      actions: read            # Required to upload SARIF file to CodeQL
      security-events: write   # Require writing security events to upload
      contents: read           # for checkout
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@8deb546fdb875b9996d27d4950be7312dac076a1" # v2.5.0
