name: "Terraform checks"
on:
  push:
    branches:
      - main
  pull_request:
    paths: ["**/*.tf", "**/*.hcl", ".github/workflows/terraform.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  AWS_REGION: eu-west-1
jobs:
  verify_module:
    name: Verify module
    strategy:
      matrix:
        terraform: ["1.5.6", "latest"]
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: "Fake zip files" # Validate will fail if it cannot find the zip files
        run: |
          touch lambdas/functions/webhook/webhook.zip
          touch lambdas/functions/control-plane/runners.zip
          touch lambdas/functions/gh-agent-syncer/runner-binaries-syncer.zip
          touch lambdas/functions/ami-housekeeper/ami-housekeeper.zip
          touch lambdas/functions/termination-watcher/termination-watcher.zip
      - name: terraform init
        run: terraform init -get -backend=false -input=false
      - if: contains(matrix.terraform, '1.5.')
        name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
      - if: contains(matrix.terraform, 'latest') # check formatting for the latest release but avoid failing the build
        name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
        continue-on-error: true
      - name: validate terraform
        run: terraform validate
      - if: contains(matrix.terraform, '1.5.')
        name: Fix for actions/cache on alpine
        run: apk add --no-cache tar
        continue-on-error: true
      - if: contains(matrix.terraform, '1.5.')
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Cache TFLint plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - if: contains(matrix.terraform, '1.5.')
        name: Setup TFLint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - if: contains(matrix.terraform, '1.5.')
        name: Run TFLint
        run: |
          tflint --init -c ${GITHUB_WORKSPACE}/.tflint.hcl
          tflint -c ${GITHUB_WORKSPACE}/.tflint.hcl --var-file ${GITHUB_WORKSPACE}/.github/lint/tflint.tfvars

  verify_modules:
    name: Verify modules
    strategy:
      fail-fast: false
      matrix:
        terraform: ["1.5.6", "latest"]
        module:
          [
            "ami-housekeeper",
            "download-lambda",
            "lambda",
            "multi-runner",
            "runner-binaries-syncer",
            "runners",
            "setup-iam-permissions",
            "ssm",
            "termination-watcher",
            "webhook",
          ]
    defaults:
      run:
        working-directory: modules/${{ matrix.module }}
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: terraform init
        run: terraform init -get -backend=false -input=false
      - if: contains(matrix.terraform, '1.3.')
        name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
      - if: contains(matrix.terraform, 'latest') # check formatting for the latest release but avoid failing the build
        name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
        continue-on-error: true
      - name: validate terraform
        run: terraform validate
      - if: contains(matrix.terraform, '1.3.')
        name: Fix for actions/cache on alpine
        run: apk add --no-cache tar
        continue-on-error: true
      - if: contains(matrix.terraform, '1.3.')
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Cache TFLint plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - if: contains(matrix.terraform, '1.3.')
        name: Setup TFLint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - if: contains(matrix.terraform, '1.3.')
        name: Run TFLint
        working-directory: ${{ github.workspace }}
        env:
          MODULE_NAME: ${{ matrix.module }}
        run: |
          tflint --init -c ${GITHUB_WORKSPACE}/.tflint.hcl --chdir "modules/${MODULE_NAME}"
          tflint -f compact -c ${GITHUB_WORKSPACE}/.tflint.hcl --var-file ${GITHUB_WORKSPACE}/.github/lint/tflint.tfvars --chdir "modules/${MODULE_NAME}"

  verify_examples:
    name: Verify examples
    strategy:
      fail-fast: false
      matrix:
        terraform: ["1.5.6", "latest"]
        example:
          [
            "default",
            "prebuilt",
            "ephemeral",
            "termination-watcher",
            "multi-runner",
            "external-managed-ssm-secrets"
          ]
    defaults:
      run:
        working-directory: examples/${{ matrix.example }}
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: terraform init
        run: terraform init -get -backend=false -input=false
      - if: contains(matrix.terraform, '1.5.')
        name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
      - if: contains(matrix.terraform, 'latest') # check formatting for the latest release but avoid failing the build
        name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
        continue-on-error: true
      - name: validate terraform
        run: terraform validate
      - if: contains(matrix.terraform, '1.5.')
        name: Fix for actions/cache on alpine
        run: apk add --no-cache tar
        continue-on-error: true
      - if: contains(matrix.terraform, '1.5.')
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Cache TFLint plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - if: contains(matrix.terraform, '1.5.')
        name: Setup TFLint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - if: contains(matrix.terraform, '1.5.')
        name: Run TFLint
        working-directory: ${{ github.workspace }}
        env:
          EXAMPLE_NAME: ${{ matrix.example }}
        run: |
          tflint --init -c ${GITHUB_WORKSPACE}/.tflint.hcl --chdir "examples/${EXAMPLE_NAME}"
          tflint -f compact -c ${GITHUB_WORKSPACE}/.tflint.hcl --var-file ${GITHUB_WORKSPACE}/.github/lint/tflint.tfvars --chdir "examples/${EXAMPLE_NAME}"

  terraform_test:
    name: Terraform test
    strategy:
      fail-fast: false
      matrix:
        module:
          - modules/runners
    defaults:
      run:
        working-directory: ${{ matrix.module }}
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform@sha256:1d10ec4073f4ddbdf34a28540a3b9250852ab500cb1c53f68c8bd17d82f474d8 # 1.14
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: terraform init
        run: terraform init -backend=false -input=false
      - name: terraform test
        run: terraform test -test-directory=tests
